version: '3.9'
services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: nest_mongo_app
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
